/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Color;
import javax.swing.JPanel;

/**
 *
 * @author AB
 */
public class Home extends javax.swing.JFrame {

    /**
     * Creates new form Home
     */
    public Home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pHeader = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        lbHomeExit = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel17 = new javax.swing.JLabel();
        pHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lbHome = new javax.swing.JLabel();
        pStudents = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        lbStudents = new javax.swing.JLabel();
        pTimetable = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        lbTimetable = new javax.swing.JLabel();
        pSettings = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        lbSettings = new javax.swing.JLabel();
        pClasses = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        lbClasses = new javax.swing.JLabel();
        pUpdate = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        lbUpdate = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pHeader.setBackground(new java.awt.Color(45, 118, 232));
        pHeader.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                pHeaderMouseDragged(evt);
            }
        });
        pHeader.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pHeaderMousePressed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Verdana", 1, 48)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("AB");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("School Management");

        lbHomeExit.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        lbHomeExit.setForeground(new java.awt.Color(255, 255, 255));
        lbHomeExit.setText("X");
        lbHomeExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                exitMousePressed(evt);
            }
        });

        jTextField1.setBackground(new java.awt.Color(45, 118, 232));
        jTextField1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setBorder(null);

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_images/search_20px_1.png"))); // NOI18N

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_images/navigation.png"))); // NOI18N

        javax.swing.GroupLayout pHeaderLayout = new javax.swing.GroupLayout(pHeader);
        pHeader.setLayout(pHeaderLayout);
        pHeaderLayout.setHorizontalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pHeaderLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbHomeExit))
            .addGroup(pHeaderLayout.createSequentialGroup()
                .addGroup(pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pHeaderLayout.createSequentialGroup()
                        .addGap(255, 255, 255)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                            .addComponent(jTextField1)))
                    .addGroup(pHeaderLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))))
                .addContainerGap(241, Short.MAX_VALUE))
        );
        pHeaderLayout.setVerticalGroup(
            pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHeaderLayout.createSequentialGroup()
                .addGroup(pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pHeaderLayout.createSequentialGroup()
                        .addComponent(lbHomeExit)
                        .addGap(152, 152, 152)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pHeaderLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(pHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(pHeaderLayout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(11, 11, 11)
                                .addComponent(jLabel14))
                            .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel16)))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(pHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 850, 200));

        pHome.setBackground(java.awt.SystemColor.controlHighlight);
        pHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pHomeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pHomeMouseExited(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_images/home_48px.png"))); // NOI18N

        lbHome.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbHome.setForeground(new java.awt.Color(45, 118, 232));
        lbHome.setText("Home");

        javax.swing.GroupLayout pHomeLayout = new javax.swing.GroupLayout(pHome);
        pHome.setLayout(pHomeLayout);
        pHomeLayout.setHorizontalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHomeLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbHome)
                    .addComponent(jLabel1))
                .addGap(27, 27, 27))
        );
        pHomeLayout.setVerticalGroup(
            pHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbHome)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jPanel1.add(pHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 230, 120, 110));

        pStudents.setBackground(java.awt.SystemColor.controlHighlight);
        pStudents.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pStudentsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pStudentsMouseExited(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_images/group_52px.png"))); // NOI18N

        lbStudents.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbStudents.setForeground(new java.awt.Color(45, 118, 232));
        lbStudents.setText("Students");

        javax.swing.GroupLayout pStudentsLayout = new javax.swing.GroupLayout(pStudents);
        pStudents.setLayout(pStudentsLayout);
        pStudentsLayout.setHorizontalGroup(
            pStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStudentsLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(pStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbStudents)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32))
        );
        pStudentsLayout.setVerticalGroup(
            pStudentsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pStudentsLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbStudents)
                .addContainerGap())
        );

        jPanel1.add(pStudents, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 230, 120, 110));

        pTimetable.setBackground(java.awt.SystemColor.controlHighlight);
        pTimetable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pTimetableMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pTimetableMouseExited(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_images/classroom_48px.png"))); // NOI18N

        lbTimetable.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbTimetable.setForeground(new java.awt.Color(45, 118, 232));
        lbTimetable.setText("Timetable");

        javax.swing.GroupLayout pTimetableLayout = new javax.swing.GroupLayout(pTimetable);
        pTimetable.setLayout(pTimetableLayout);
        pTimetableLayout.setHorizontalGroup(
            pTimetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTimetableLayout.createSequentialGroup()
                .addGroup(pTimetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pTimetableLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel5))
                    .addGroup(pTimetableLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(lbTimetable)))
                .addGap(26, 26, 26))
        );
        pTimetableLayout.setVerticalGroup(
            pTimetableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pTimetableLayout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbTimetable)
                .addContainerGap())
        );

        jPanel1.add(pTimetable, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 230, 120, 110));

        pSettings.setBackground(java.awt.SystemColor.controlHighlight);
        pSettings.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pSettingsMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pSettingsMouseExited(evt);
            }
        });

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_images/settings_48px.png"))); // NOI18N

        lbSettings.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbSettings.setForeground(new java.awt.Color(45, 118, 232));
        lbSettings.setText("Settings");

        javax.swing.GroupLayout pSettingsLayout = new javax.swing.GroupLayout(pSettings);
        pSettings.setLayout(pSettingsLayout);
        pSettingsLayout.setHorizontalGroup(
            pSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSettingsLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbSettings)
                    .addComponent(jLabel7))
                .addGap(36, 36, 36))
        );
        pSettingsLayout.setVerticalGroup(
            pSettingsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pSettingsLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbSettings)
                .addContainerGap())
        );

        jPanel1.add(pSettings, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 360, 120, 110));

        pClasses.setBackground(java.awt.SystemColor.controlHighlight);
        pClasses.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pClassesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pClassesMouseExited(evt);
            }
        });
        pClasses.setLayout(null);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_images/list_64px.png"))); // NOI18N
        pClasses.add(jLabel9);
        jLabel9.setBounds(30, 10, 70, 70);

        lbClasses.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbClasses.setForeground(new java.awt.Color(45, 118, 232));
        lbClasses.setText("Classes");
        pClasses.add(lbClasses);
        lbClasses.setBounds(40, 80, 50, 17);

        jPanel1.add(pClasses, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 360, 120, 110));

        pUpdate.setBackground(java.awt.SystemColor.controlHighlight);
        pUpdate.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pUpdateMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pUpdateMouseExited(evt);
            }
        });

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main_images/download_52px.png"))); // NOI18N

        lbUpdate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lbUpdate.setForeground(new java.awt.Color(45, 118, 232));
        lbUpdate.setText("Update");

        javax.swing.GroupLayout pUpdateLayout = new javax.swing.GroupLayout(pUpdate);
        pUpdate.setLayout(pUpdateLayout);
        pUpdateLayout.setHorizontalGroup(
            pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateLayout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbUpdate)
                    .addComponent(jLabel11))
                .addGap(32, 32, 32))
        );
        pUpdateLayout.setVerticalGroup(
            pUpdateLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUpdateLayout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbUpdate)
                .addContainerGap())
        );

        jPanel1.add(pUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 360, 120, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void exitMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMousePressed
        System.exit(0);
    }//GEN-LAST:event_exitMousePressed

    private void pHomeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHomeMouseEntered
        setColor(pHome);
    }//GEN-LAST:event_pHomeMouseEntered

    private void pHomeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHomeMouseExited
        resetColor(pHome);
    }//GEN-LAST:event_pHomeMouseExited

    int xx, xy;
    private void pHeaderMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHeaderMousePressed
        xx = evt.getX();
        xy = evt.getY();
    }//GEN-LAST:event_pHeaderMousePressed

    private void pHeaderMouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pHeaderMouseDragged
        int x = evt.getXOnScreen();
        int y = evt.getYOnScreen();
        this.setLocation(x - xx, y - xy);
    }//GEN-LAST:event_pHeaderMouseDragged

    private void pStudentsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pStudentsMouseEntered
        setColor(pStudents);
    }//GEN-LAST:event_pStudentsMouseEntered

    private void pStudentsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pStudentsMouseExited
        resetColor(pStudents);
    }//GEN-LAST:event_pStudentsMouseExited

    private void pTimetableMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTimetableMouseEntered
        setColor(pTimetable);
    }//GEN-LAST:event_pTimetableMouseEntered

    private void pTimetableMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pTimetableMouseExited
        resetColor(pTimetable);
    }//GEN-LAST:event_pTimetableMouseExited

    private void pSettingsMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSettingsMouseEntered
        setColor(pSettings);
    }//GEN-LAST:event_pSettingsMouseEntered

    private void pSettingsMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pSettingsMouseExited
        resetColor(pSettings);
    }//GEN-LAST:event_pSettingsMouseExited

    private void pClassesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pClassesMouseEntered
        setColor(pClasses);
    }//GEN-LAST:event_pClassesMouseEntered

    private void pClassesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pClassesMouseExited
        resetColor(pClasses);
    }//GEN-LAST:event_pClassesMouseExited

    private void pUpdateMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pUpdateMouseEntered
        setColor(pUpdate);
    }//GEN-LAST:event_pUpdateMouseEntered

    private void pUpdateMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pUpdateMouseExited
        resetColor(pUpdate);
    }//GEN-LAST:event_pUpdateMouseExited

    public void setColor(JPanel panel) {
        panel.setBackground(new Color(197, 197, 197));
    }

    public void resetColor(JPanel panel) {
        panel.setBackground(new Color(240, 240, 240));
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Home().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lbClasses;
    private javax.swing.JLabel lbHome;
    private javax.swing.JLabel lbHomeExit;
    private javax.swing.JLabel lbSettings;
    private javax.swing.JLabel lbStudents;
    private javax.swing.JLabel lbTimetable;
    private javax.swing.JLabel lbUpdate;
    private javax.swing.JPanel pClasses;
    private javax.swing.JPanel pHeader;
    private javax.swing.JPanel pHome;
    private javax.swing.JPanel pSettings;
    private javax.swing.JPanel pStudents;
    private javax.swing.JPanel pTimetable;
    private javax.swing.JPanel pUpdate;
    // End of variables declaration//GEN-END:variables
}
